# Generated by Django 5.2 on 2025-04-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_remove_watchlist_after_hours_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='revenue',
            new_name='listed_shares',
        ),
    ]
